spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/timeattendance
    username: postgres
    password: Alcohol145.
  jpa:
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: us2.smtp.mailhostbox.com
    username: reportes@doce.do
    password: bem@!Vt2
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
mail:
  sender: SES
  ses:
    fromAddress: Reportes de Asistencia <reportes@doce.io>
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      accessKey: AKIAXJ2VXKUI5JSYE5FC
      secretKey: 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
    sqs:
      api-queue: api-doce-local
      device-queue: device-doce-local
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE:
        SQL=DEBUG:
