spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/timeattendance
    username: postgres
    password: Alcohol145.
mail:
  sender: JAVA
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      accessKey: AKIA3U2JKO4T27DYS7ET
      secretKey: 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
    sqs:
      api-queue: doce-api-local
      device-queue: doce-device-local
